name: Android

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  test:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'
      - name: Build debug
        run: |
          touch local.properties
          echo "publicApiKey=plug\nprivateApiKey=plug" >> local.properties
          bash ./gradlew build jacocoTestReport assembleAndroidTest
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck
      - name: Upload coverage to Codecov
        run: |
          curl -Os https://uploader.codecov.io/latest/macos/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
